package pojo;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;

import dao.AdminDAO;

// default package
// Generated Sep 22, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

/**
 * Admin generated by hbm2java
 */
@ManagedBean
@Entity
public class Admin implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idadmin;
	private String username;
	private String password;
	private String fullname;
	private String email;
	private String status;

	@Transient
	private int selectedID;

	@Transient
	private String temppassword;
	
	@Transient
	private String msg;

	public Admin() {
	}

	public Admin(String username, String password, String fullname, String email, String status) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.email = email;
		this.status = status;
	}
	
	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getTemppassword() {
		return temppassword;
	}

	public void setTemppassword(String temppassword) {
		this.temppassword = temppassword;
	}

	public int getSelectedID() {
		return selectedID;
	}

	public void setSelectedID(int selectedID) {
		this.selectedID = selectedID;
	}

	public Integer getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(Integer idadmin) {
		this.idadmin = idadmin;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void addNewAdmin() {
		AdminDAO dao = new AdminDAO();
		setStatus("Aktif");
		if (checkPassword()==true) {
			dao.addNewAdmin(this);
			clearAll();
		} else {
			clearAll();
		}
	}

	public boolean checkPassword() {
		if (password.equals(temppassword)) {
			return true;
		} else {
			return false;
		}
	}

	public List<Admin> getAllAdmin() {
		AdminDAO dao = new AdminDAO();
		return dao.getAllAdmin();
	}

	public List<Admin> getAllAdminID() {
		AdminDAO dao = new AdminDAO();
		return dao.getAllAdminID();
	}

	public void getAdminById() {
		System.out.println(selectedID);
		AdminDAO dao = new AdminDAO();
		Admin k = dao.getAdminById(this);
		setIdadmin(k.idadmin);
		setEmail(k.email);
		setUsername(k.username);
		setPassword(k.password);
		setStatus(k.status);
		setFullname(k.fullname);
		setTemppassword(k.password);
	}

	public void updateAdmin() {
		AdminDAO dao = new AdminDAO();
		setIdadmin(selectedID);
		if(checkPassword()==true) {
			dao.updateAdmin(this);
			clearAll();
		} else {
			clearAll();
		}
	}

	public void deleteAdmin() {
		AdminDAO dao = new AdminDAO();
		setIdadmin(selectedID);
		dao.deleteAdmin(this);
		clearAll();
	}

	public String validateLogin() {
		AdminDAO dao = new AdminDAO();
		List<Admin> login = dao.validateLogin(this);
		boolean loginSuccess;

		System.out.println("akun yg berhasil di validasi = " + login.size());

		if (login.size() == 1) {
			loginSuccess = true;
		} else {
			loginSuccess = false;
		}

		if (loginSuccess == true) {
			return "index";
		} else {
			return "login";
		}

	}

	public void clearAll() {
		setIdadmin(null);
		setEmail(null);
		setUsername(null);
		setPassword(null);
		setStatus(null);
		setFullname(null);
	}

	@Override
	public String toString() {
		return "Admin [idadmin=" + idadmin + ", username=" + username + ", password=" + password + ", fullname="
				+ fullname + ", email=" + email + ", status=" + status + ", selectedID=" + selectedID
				+ ", temppassword=" + temppassword + ", msg=" + msg + "]";
	}
	
	

}
